# Generated by Django 4.0.5 on 2022-06-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filemgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiledDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtable_number', models.IntegerField()),
                ('tile_count_on_x', models.IntegerField()),
                ('tile_count_on_y', models.IntegerField()),
                ('total_tile_count', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemgr.document')),
            ],
        ),
    ]
